Added new classes and functions in DOCX part of library
LISA-ITMO/Python-Documents-Modifier pull request #7
Opened 2024-04-19 19:39 UTC by MrAmfix

Added XMLRedactor class for editing lists styles and editing or removing comments.
Added the same methods in DOCXRedactor class.
Also have been added some new enum-classes and exception-classes

2024-04-19 19:40 UTC, MrAmfix commented
Добавлю тесты чуть позже

2024-04-23 19:51 UTC, Vl-Tershch reviewed
example - копия.zip - что это и зачем нужно? Если нужно - то переименовать, русских символов не должно быть в названиях.

2024-04-23 20:36 UTC, MrAmfix commented
> example - копия.zip - что это и зачем нужно? Если нужно - то переименовать, русских символов не должно быть в названиях.

Да, я забыл удалить этот архив, в нем проверял что все внутри правильно изменилось. Больше ничего?

2024-04-23 22:31 UTC, slavamarcin requested changes
Вкратце что заметил. По методам есть моменты которые нужно будет оптимизировать.

2024-04-23 22:31 UTC, slavamarcin commented on examples/docx/example — копия.zip
Зачем здесь данный файл

2024-04-23 22:31 UTC, slavamarcin commented on src/docx/docx_redactor.py
> +            raise ParagraphNotFound(paraId)
Не совсем понял зачем здесь флаги, можно использовать конструкцию for else, если не хочешь возвращать какие - либо переменные

2024-04-23 22:31 UTC, slavamarcin commented on src/docx/docx_redactor.py
> +                         document=None) -> None:
Зачем указываешь тип возвращаемого значения если ты ничего не возвращаешь

2024-04-23 22:31 UTC, slavamarcin commented on src/docx/xml_redactor.py
> +            8: (6480, 360)
Не факт что они всегда будут такими, т.к. этот показатель может зависеть от текстового редактора

2024-04-23 22:31 UTC, slavamarcin commented on src/docx/xml_redactor.py
> +                    if element.attrib[f'{{{schemas.w}}}id'] == str(comment_id):
нужно добавить проверку на существование ключа

2024-04-23 22:31 UTC, slavamarcin commented on src/docx/xml_redactor.py
> +                            if sub_elem.attrib[f'{{{schemas.w}}}id'] == str(comment_id):
То же самое

2024-04-23 22:31 UTC, slavamarcin commented on src/docx/xml_redactor.py
> +                            if sub_elem.attrib[f'{{{schemas.w}}}id'] == str(comment_id):
Можно сделать как ранее ты делал через KeyError

2024-04-23 22:31 UTC, slavamarcin commented on src/docx/xml_redactor.py
> +        root = tree.getroot()
второй раз вижу этот же код, вынеси в отдельный метод

2024-04-23 22:31 UTC, slavamarcin commented on src/docx/xml_redactor.py
> +                    comment.attrib[f'{{{schemas.w}}}author'] = new_author
То же самое, нужно добавить проверку наличия ключа

2024-04-23 22:31 UTC, slavamarcin commented on src/docx/xml_redactor.py
> +        return paragraphs
Зачем этот метод нужен? Он где-то используется?

2024-04-24 12:22 UTC, MrAmfix commented on src/docx/xml_redactor.py
> +            8: (6480, 360)
Это стандартные отступы и кастомные отступы неоткуда вытаскивать, так что оставлю такие

2024-04-24 12:23 UTC, MrAmfix commented on src/docx/xml_redactor.py
> +                    if element.attrib[f'{{{schemas.w}}}id'] == str(comment_id):
Тут это не имеет смысла, так как у commentRangeStart/End всегда есть атрибут id

2024-04-24 12:23 UTC, MrAmfix commented on src/docx/xml_redactor.py
> +                            if sub_elem.attrib[f'{{{schemas.w}}}id'] == str(comment_id):
Тут это тоже не имеет смысла, commentReference всегда имеет id

2024-04-24 12:23 UTC, slavamarcin commented on src/docx/xml_redactor.py
> +            8: (6480, 360)
Да, но это всё-таки костыли, можно сделать в функции просто входные переменные для данных параметров )))

2024-04-24 12:24 UTC, MrAmfix commented on src/docx/xml_redactor.py
> +                    comment.attrib[f'{{{schemas.w}}}author'] = new_author
Не имеет смысла, у комментариев всегда есть автор

2024-04-24 12:24 UTC, slavamarcin commented on src/docx/xml_redactor.py
> +                    if element.attrib[f'{{{schemas.w}}}id'] == str(comment_id):
бывают ситуации когда коммент в xml есть, но на него нет ссылки и у него нет id (когда обрабатывал файлы docx периодически попадались ситуации с другими элементами, когда id должен быть но его нет)

2024-04-24 12:25 UTC, MrAmfix commented on src/docx/xml_redactor.py
> +        return paragraphs
В целом он не нужен, но используется для наглядность в примерах, чтобы вытащить paraId

2024-04-27 17:45 UTC, MrAmfix commented on src/docx/docx_redactor.py
> +            raise ParagraphNotFound(paraId)
Флаг здесь нужен. For else не подойдет

2024-05-14 15:47 UTC, slavamarcin approved these changes

2024-05-29 13:09 UTC, merged