Eaf d 2  2 library for edit odt
LISA-ITMO/Python-Documents-Modifier pull request #8
Opened 2024-05-21 18:37 UTC by Inf1nity2483

Deleted models.py, moved its contents to enums.py. Added missing comments describing functions and classes.

2024-05-23 20:13 UTC, slavamarcin requested changes

2024-05-23 20:13 UTC, slavamarcin commented on src/odt/enum/annotation.py
Не совсем понял почему он в папке enum

2024-05-23 20:13 UTC, slavamarcin commented on src/odt/odtredactor.py
> +        self.stringroot = ET.fromstring(self.data['content.xml'].decode('UTF-8'))
кодировку лучше передавать в параметре

2024-05-23 20:13 UTC, slavamarcin commented on src/odt/odtredactor.py
> +        self.stringroot = ET.fromstring(self.data['content.xml'].decode('UTF-8'))
лучше вынести из этого метода и сделать метод для выделения root, как раз с указанием имени файла, xml которого нам нужно получить и кодировки

2024-05-23 20:13 UTC, slavamarcin commented on src/odt/odtredactor.py
> +        self.data = file_data
Может быть лучше сделать данный метод статическим и возвращать filedata, и соответственно в init его записывать в переменную класса

2024-05-23 20:13 UTC, slavamarcin commented on src/odt/odtredactor.py
> +        for p in self.stringroot.iter(Styles.PARAGRAPH):
зачем здесь 2 такой же цикл?

2024-05-23 20:13 UTC, slavamarcin commented on src/odt/odtredactor.py
> +        return '\n'.join(text)
где-то используется, непонятно зачем здесь нужен

2024-05-23 20:13 UTC, slavamarcin commented on src/odt/odtredactor.py
> +            i.text = None
где-то используется?

2024-05-24 14:34 UTC, Inf1nity2483 commented on src/odt/odtredactor.py
> +        for p in self.stringroot.iter(Styles.PARAGRAPH):
Аннотация делится на 2 объекта: начало и конец. Первый цикл удаляет начало аннотации и записывает её id, второй ищет конец аннотации по id и удаляет его

2024-06-01 20:19 UTC, Vl-Tershch approved these changes

2024-06-01 20:23 UTC, slavamarcin approved these changes

2024-06-01 20:23 UTC, merged